[package]
name = "smart_alt_codes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
csv = "1.1.6"
enigo = "0.0.14"
